# vim: ts=2 sw=2 et :
---
version: '3.8'
services:
   web:
       build:
         context: .
         dockerfile: Dockerfile
       command: /app/manage.py runserver 0.0.0.0:8081
       ports:
         - "8081:8081"
